# Clippy configuration for strict linting

# Complexity limits
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 5
type-complexity-threshold = 250

# Pedantic lints to allow (reduce noise)
allow-expect-in-tests = true
allow-unwrap-in-tests = true

# Performance and correctness
warn-on-all-wildcard-imports = true