# Rust formatting configuration (stable features only)

# Edition and style
edition = "2021"

# Line length and indentation
max_width = 100
hard_tabs = false
tab_spaces = 4

# Other stable formatting options
match_block_trailing_comma = false